forge "https://forgeapi.puppetlabs.com"

# Module for access to NSIDC Enterprise storage
mod "nsidc/nsidc_nfs",
  :git => "git@bitbucket.org:/nsidc/puppet-nsidc-nfs.git"

# Module for creating NSIDC Jenkins servers
mod "nsidc/nsidc_jenkins",
  :git => "git@bitbucket.org:/nsidc/puppet-nsidc-jenkins.git",
  :ref => 'latest'

mod 'nsidc/nginx',
  :git => 'git@bitbucket.org:nsidc/puppet-nginx.git'

mod "nsidc/nsidc_os_repo",
  :git  => "git@bitbucket.org:/nsidc/puppet-nsidc-os-repo.git",
  :ref  => "latest"

mod 'puppetlabs/concat', "1.2.3"
mod 'p0deje/firefox'
mod 'puppetlabs/apt', "1.8.0"
mod 'puppetlabs/ruby'
mod 'willdurand/nodejs'
